/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RitualsRouteImport } from './routes/rituals'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as IndexRouteImport } from './routes/index'

const RitualsRoute = RitualsRouteImport.update({
  id: '/rituals',
  path: '/rituals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/journal': typeof JournalRoute
  '/philosophy': typeof PhilosophyRoute
  '/products': typeof ProductsRoute
  '/rituals': typeof RitualsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/journal': typeof JournalRoute
  '/philosophy': typeof PhilosophyRoute
  '/products': typeof ProductsRoute
  '/rituals': typeof RitualsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/journal': typeof JournalRoute
  '/philosophy': typeof PhilosophyRoute
  '/products': typeof ProductsRoute
  '/rituals': typeof RitualsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/journal' | '/philosophy' | '/products' | '/rituals'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/journal' | '/philosophy' | '/products' | '/rituals'
  id: '__root__' | '/' | '/journal' | '/philosophy' | '/products' | '/rituals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JournalRoute: typeof JournalRoute
  PhilosophyRoute: typeof PhilosophyRoute
  ProductsRoute: typeof ProductsRoute
  RitualsRoute: typeof RitualsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rituals': {
      id: '/rituals'
      path: '/rituals'
      fullPath: '/rituals'
      preLoaderRoute: typeof RitualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JournalRoute: JournalRoute,
  PhilosophyRoute: PhilosophyRoute,
  ProductsRoute: ProductsRoute,
  RitualsRoute: RitualsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
